"""empty message

Revision ID: 180d985cfad2
Revises: 65ca9f45b773
Create Date: 2022-06-14 13:14:37.787833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '180d985cfad2'
down_revision = '65ca9f45b773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE user_types ADD VALUE 'basic'")
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('manager', 'admin', 'researcher', 'basic', name='user_types'),
               nullable=False,
               existing_server_default=sa.text("'researcher'::user_types"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM user_types WHERE enumlabel = 'basic'")
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('manager', 'admin', 'researcher', name='user_types'),
               nullable=True,
               existing_server_default=sa.text("'researcher'::user_types"))
    # ### end Alembic commands ###
