"""empty message

Revision ID: ebdc63a49615
Revises: 180d985cfad2
Create Date: 2022-06-14 15:35:02.158590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebdc63a49615'
down_revision = '180d985cfad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_secret_key'), 'secret', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secret_key'), table_name='secret')
    op.drop_table('secret')
    # ### end Alembic commands ###
